<script setup lang="ts">
const features = [
	{
		title: 'Brand Hub & Guidelines',
		description: 'Train the agent in your brand visual identity, tone & voice, styles, and rules.',
		media: 'https://www.kyoso.com/video/brand-knowledge.webm',
	},
	{
		title: 'Discovery & Inspiration',
		description: 'Find inspiring content generated by agent for your brand and other users.',
		media: 'https://www.kyoso.com/video/discovery.webm',
	},
	{
		title: 'Animation Model',
		description: 'The first advanced 2D animation model in the creative AI industry. Simply ask for the animation,or take full control.',
		media: 'https://www.kyoso.com/video/animation-model.webm',
	},
	{
		title: 'Real-world data and trends analysis',
		description: 'Leverage engagement, marketing, and global trend data to create timely, relevant content.',
		media: 'https://www.kyoso.com/video/trends.webm',
	},
	{
		title: 'Fine-control',
		description: 'Gain control over the output, timeline, and get access to the advanced fine-tuning tools like LoRA style creation.',
		media: 'https://www.kyoso.com/video/control.webm',
	},
	{
		title: 'Private & Secure',
		description: 'All data stay yours and secured by the state-of-art data-protection standards.',
		media: 'https://www.kyoso.com/video/security-privacy.webm',
	},
];
</script>

<template>
	<div class="grid md:grid-cols-2 gap-x-6 gap-y-10 md:gap-y-20 w-full">
		<div
			v-for="(feature, index) in features"
			:key="index"
			class="flex flex-col gap-6"
		>
			<div class="bg-[#171717] aspect-square rounded-4xl overflow-clip">
				<video
					class="w-full h-full object-cover aspect-square"
					loop
					playsinline
					preload="none"
					:src="feature.media"
				/>
			</div>
			<div class="px-2 max-w-[480px]">
				<h3 class="text-white font-medium text-base md:text-xl leading-relaxed">
					{{ feature.title }}
				</h3>
				<p class="text-white/50 font-medium text-base md:text-xl leading-relaxed">
					{{ feature.description }}
				</p>
			</div>
		</div>
	</div>
</template>
